### ISSUE TITLE
Add stable tags versions

### ISSUE THREAD

**Issue by necromant2005** [kraken-io/kraken-php#10]
The next step after composer.json is adding stable version releases through git tag e.g.
release-1.0
release-1.1
...
release-2.x
etc.

**Comment by necromant2005** [comment]
Nothing changed: https://github.com/kraken-io/kraken-php/releases
You need to push your changes:

git push origin tag-name:tag-name

for example for "release-1.0" it will be 
git tag release-1.0
git push origin release-1.0:release-1.0

Only after that tags will be available.

**Comment by stof** [comment]
@kraken-io ``release-1.0`` is not a tag name accepted by Composer. It expects tags named after the semver version. So it can be ``1.0`` or ``v1.0``, but not ``release-1.0``

**Comment by tixastronauta** [comment]
:+1: @stof 

Tags should follow [Semantic Versioning 2.0.0](http://semver.org/).

**Comment by stof** [comment]
Actually, it looks like composer now accepts ``release-`` as prefix too: https://packagist.org/packages/kraken-io/kraken-php
