### ISSUE TITLE
Add support for curl timeout

### ISSUE THREAD

**Issue by G4MR** [kraken-io/kraken-php#14]
Something like the following:

    class Kraken 
    {
        protected $timeout              = 0;
        protected $connection_timeout   = 0;

        <snipped>

        public function setTimeout($seconds)
        {
            $this->timeout = $seconds;
        }

        public function setConnectionTimeout($seconds)
        {
            $this->connection_timeout = $seconds;
        }

        private function request($data, $url, $type) 
        {
            $curl = curl_init();
            if ($type === 'url') {
                curl_setopt($curl, CURLOPT_HTTPHEADER, array(
                    'Content-Type: application/json'
                ));
            }
            curl_setopt($curl, CURLOPT_URL, $url);
            
            // Force continue-100 from server
            curl_setopt($curl, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36");
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
            curl_setopt($curl, CURLOPT_FAILONERROR, 0);

            //set connection timeout if value is greater than zero
            if($this->connection_timeout > 0) {
                curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, $this->connection_timeout);
            }

            //set timeout if value is greater than zero
            if($this->timeout > 0) {
                curl_setopt($curl, CURLOPT_TIMEOUT, $this->timeout);
            }

            $response = json_decode(curl_exec($curl), true);
            if ($response === null) {
                $response = array (
                    "success" => false,
                    "error" => 'cURL Error: ' . curl_error($curl)
                );
            }
            
            curl_close($curl);
            return $response;
        }

    }

You can see my additions as I snipped some of the code out for reading purposes eg.:

    protected $timeout              = 0;
    protected $connection_timeout   = 0;

and

    public function setTimeout($seconds)
    {
        $this->timeout = $seconds;
    }

    public function setConnectionTimeout($seconds)
    {
        $this->connection_timeout = $seconds;
    }

As well as:

    //set connection timeout if value is greater than zero
    if($this->connection_timeout > 0) {
        curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, $this->connection_timeout);
    }

    //set timeout if value is greater than zero
    if($this->timeout > 0) {
        curl_setopt($curl, CURLOPT_TIMEOUT, $this->timeout);
    }

I'm going to write a PR as soon as possible.

**Comment by matylla** [comment]
This issue has been addressed and fixed in #15.
