### ISSUE TITLE
cURL error due to AddTrust root certificate expiration

### ISSUE THREAD

**Issue by themreza** [kraken-io/kraken-php#20]
On May 30th, 2020, the AddTrust root certificate expired and has caused connectivity issues in many services. https://packetstormsecurity.com/files/157891/Ubuntu-Security-Notice-USN-4377-1.html

This repository uses its own certificate bundle https://github.com/kraken-io/kraken-php/blob/master/lib/cacert.pem which is now outdated and causes cURL requests to fail https://github.com/kraken-io/kraken-php/blob/master/lib/Kraken.php#L87 even though the system's certificate bundle is up-to-date.

**Comment by hhsadiq** [comment]
facing same issue, unable to use the Kraken service now. @themreza any work-around so far?

**Comment by hhsadiq** [comment]
So for now I have made following changes in https://github.com/kraken-io/kraken-php/blob/master/lib/Kraken.php, and its working now. Not sure how secure is that, but at-least able to upload images

![image](https://user-images.githubusercontent.com/8002757/83640764-07ba9f00-a5c6-11ea-9171-7ad4458e5021.png)

**Comment by MrFondant** [comment]
I've raised this as a support ticket directly with Kraken. We've been unable to upload images this way for 4+ days.

**Comment by danielsreichenbach** [comment]
Hi there, we're on this.

The proper fix for this would be:

- remove the cacert from this library
- retrieve and updated CA cert bundle from your Operating System vendor since that is where these things are maintained.

**Comment by danielsreichenbach** [comment]
Please update to commit 74dbcdb5ee08cfa1b133859f246b0e991ee55aaa and make sure you have an updated CA certificate package installed on your system. That should restore operations.

**Comment by alanwm2** [comment]
We're running into this, even by following these steps.  

It turns out that the root certificate on Kraken is expired as of 10 days ago.  Here is proof:

https://www.sslshopper.com/ssl-checker.html#hostname=dl.kraken.io

Please fix this root SSL on the Kraken domain so that we can use it.

We're able to bypass the SSL certificate issue by temporarily setting CURLOPT_SSL_VERIFYPEER to 0 however, it also fails on the copy() php command because the Kraken SSL certificate is expired.

We've sent support tickets into Kraken however we can't get a response.

**Comment by danielsreichenbach** [comment]
@alanwm2 it turned out a bunch of backend machines were still pointing to the wrong version. Just pushed a configuration update that is no propagating on all backend servers to fix this.

**Comment by alanwm2** [comment]
Thank you @danielsreichenbach, it is working now.

**Comment by danielsreichenbach** [comment]
Thanks to everyone reporting this, closing now since the certificate update has propagated to all backend servers.

**Comment by xluffy** [comment]
@danielsreichenbach Let see your SSL. So why still use SHA-1?

![image](https://user-images.githubusercontent.com/1505720/84484583-26efb580-acc5-11ea-89e9-8297adc23ce8.png)

**Comment by danielsreichenbach** [comment]
@xluffy the certificate is in the process of being renewed, that's a separate issue.
