### ISSUE TITLE
Api failed to resize img and store it to Aws S3 bucket

### ISSUE THREAD

**Issue by reydajp** [kraken-io/kraken-php#22]
Since 2 days ago and the kraken DB outage, I'm getting this error "Error while creating temporary directory in file storage." 
Any solutions please ? 
Thanks you

**Comment by vburghelea** [comment]
Sorry for the delay in getting back to you, @reydajp - I'm closing this, as it's been quite some time since the reported issue. Please reopen if this is still actual and you need further support.
