### ISSUE TITLE
Add Composer functionality

### ISSUE THREAD

**Issue by derekperkins** [kraken-io/kraken-php#6]
It's hard to use any php library these days without it being compatible with composer. Can you please list it on packagist.org and add a composer.json file?

**Comment by necromant2005** [comment]
+1 composer is necessity. I cannot install this adapter without composer config

**Comment by stof** [comment]
See #11 for a PR implementing this

**Comment by stof** [comment]
See #11 for a PR implementing this

**Comment by kraken-io** [comment]
kraken-php is now published in [Composer](https://packagist.org/packages/kraken-io/kraken-php). Thanks for your input.
